"""initial uuid schema

Revision ID: 34467fcc702f
Revises: 
Create Date: 2025-08-19 11:08:16.818730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34467fcc702f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbc_level',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbc_level'))
    )
    op.create_index(op.f('ix_cbc_level_label'), 'cbc_level', ['label'], unique=False)
    op.create_index(op.f('ix_cbc_level_school_id'), 'cbc_level', ['school_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('stream', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes'))
    )
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_table('fee_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_structures'))
    )
    op.create_index(op.f('ix_fee_structures_school_id'), 'fee_structures', ['school_id'], unique=False)
    op.create_index('ix_fee_structures_school_term_year', 'fee_structures', ['school_id', 'term', 'year'], unique=False)
    op.create_table('gl_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gl_accounts'))
    )
    op.create_index(op.f('ix_gl_accounts_school_id'), 'gl_accounts', ['school_id'], unique=False)
    op.create_table('guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('relationship', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardians'))
    )
    op.create_index(op.f('ix_guardians_school_id'), 'guardians', ['school_id'], unique=False)
    op.create_table('journalentry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journalentry'))
    )
    op.create_index(op.f('ix_journalentry_school_id'), 'journalentry', ['school_id'], unique=False)
    op.create_table('journalline',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('journal_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journalline'))
    )
    op.create_index(op.f('ix_journalline_account_id'), 'journalline', ['account_id'], unique=False)
    op.create_index(op.f('ix_journalline_journal_id'), 'journalline', ['journal_id'], unique=False)
    op.create_index(op.f('ix_journalline_school_id'), 'journalline', ['school_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('to_guardian_id', sa.String(length=36), nullable=True),
    sa.Column('to_user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_school_id'), 'notification', ['school_id'], unique=False)
    op.create_index(op.f('ix_notification_to_guardian_id'), 'notification', ['to_guardian_id'], unique=False)
    op.create_index(op.f('ix_notification_to_user_id'), 'notification', ['to_user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('roles_csv', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('roles_csv', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('fee_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('fee_structure_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('billing_cycle', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("billing_cycle IN ('TERM','ANNUAL','ONE_OFF')", name=op.f('ck_fee_items_ck_fee_items_billing_cycle')),
    sa.CheckConstraint("category IN ('TUITION','COCURRICULAR','OTHER')", name=op.f('ck_fee_items_ck_fee_items_category')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_fee_items_ck_fee_items_amount_positive')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_fee_items_class_id_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], name=op.f('fk_fee_items_fee_structure_id_fee_structures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_items'))
    )
    op.create_index(op.f('ix_fee_items_class_id'), 'fee_items', ['class_id'], unique=False)
    op.create_index(op.f('ix_fee_items_fee_structure_id'), 'fee_items', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_fee_items_school_id'), 'fee_items', ['school_id'], unique=False)
    op.create_index('ix_fee_items_school_structure_class', 'fee_items', ['school_id', 'fee_structure_id', 'class_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.Column('short_code', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('academic_year_start', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_schools_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools')),
    sa.UniqueConstraint('short_code', name=op.f('uq_schools_short_code'))
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('admission_no', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('primary_guardian_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_students_class_id_classes')),
    sa.ForeignKeyConstraint(['primary_guardian_id'], ['guardians.id'], name=op.f('fk_students_primary_guardian_id_guardians')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('admission_no', name=op.f('uq_students_admission_no'))
    )
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ISSUED','PAID','PARTIAL')", name=op.f('ck_invoices_ck_invoice_status')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_invoices_ck_invoice_total_positive')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_invoices_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_school_id'), 'invoices', ['school_id'], unique=False)
    op.create_index('ix_invoices_school_student_term', 'invoices', ['school_id', 'student_id', 'term', 'year'], unique=False)
    op.create_table('schoolmember',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('OWNER','ADMIN','TEACHER','ACCOUNTANT','PARENT')", name=op.f('ck_schoolmember_ck_schoolmember_role')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_schoolmember_school_id_schools')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_schoolmember_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schoolmember'))
    )
    op.create_table('student_guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_student_guardians_guardian_id_guardians')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_guardians_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_guardians'))
    )
    op.create_index(op.f('ix_student_guardians_guardian_id'), 'student_guardians', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_school_id'), 'student_guardians', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_id'), 'student_guardians', ['student_id'], unique=False)
    op.create_table('invoiceline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_invoiceline_ck_invoiceline_amount_positive')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoiceline_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoiceline'))
    )
    op.create_index(op.f('ix_invoiceline_school_id'), 'invoiceline', ['school_id'], unique=False)
    op.create_index('ix_invoiceline_school_invoice', 'invoiceline', ['school_id', 'invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('txn_ref', sa.String(length=64), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("method IN ('CASH','BANK','MPESA')", name=op.f('ck_payments_ck_payment_method')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_ck_payment_amount_positive')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_school_id'), 'payments', ['school_id'], unique=False)
    op.create_index('ix_payments_school_invoice', 'payments', ['school_id', 'invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_school_invoice', table_name='payments')
    op.drop_index(op.f('ix_payments_school_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_invoiceline_school_invoice', table_name='invoiceline')
    op.drop_index(op.f('ix_invoiceline_school_id'), table_name='invoiceline')
    op.drop_table('invoiceline')
    op.drop_index(op.f('ix_student_guardians_student_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_school_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_guardian_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_table('schoolmember')
    op.drop_index('ix_invoices_school_student_term', table_name='invoices')
    op.drop_index(op.f('ix_invoices_school_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('schools')
    op.drop_index('ix_fee_items_school_structure_class', table_name='fee_items')
    op.drop_index(op.f('ix_fee_items_school_id'), table_name='fee_items')
    op.drop_index(op.f('ix_fee_items_fee_structure_id'), table_name='fee_items')
    op.drop_index(op.f('ix_fee_items_class_id'), table_name='fee_items')
    op.drop_table('fee_items')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_notification_to_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_to_guardian_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_school_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_journalline_school_id'), table_name='journalline')
    op.drop_index(op.f('ix_journalline_journal_id'), table_name='journalline')
    op.drop_index(op.f('ix_journalline_account_id'), table_name='journalline')
    op.drop_table('journalline')
    op.drop_index(op.f('ix_journalentry_school_id'), table_name='journalentry')
    op.drop_table('journalentry')
    op.drop_index(op.f('ix_guardians_school_id'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_gl_accounts_school_id'), table_name='gl_accounts')
    op.drop_table('gl_accounts')
    op.drop_index('ix_fee_structures_school_term_year', table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_school_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_cbc_level_school_id'), table_name='cbc_level')
    op.drop_index(op.f('ix_cbc_level_label'), table_name='cbc_level')
    op.drop_table('cbc_level')
    # ### end Alembic commands ###
