"""fix_school_model_year_start

Revision ID: 5b36301167e6
Revises: 4e15be3ae4b4
Create Date: 2025-08-19 11:43:03.561900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b36301167e6'
down_revision: Union[str, Sequence[str], None] = '4e15be3ae4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    
    # FIXED: Handle the academic_year_start type change with explicit conversion
    # Step 1: Add a temporary date column
    op.add_column('schools', sa.Column('academic_year_start_temp', sa.Date(), nullable=True))
    
    # Step 2: Convert integer years to dates (assuming January 1st as start date)
    op.execute("""
        UPDATE schools 
        SET academic_year_start_temp = MAKE_DATE(academic_year_start, 1, 1)
        WHERE academic_year_start IS NOT NULL
    """)
    
    # Step 3: Drop the old integer column
    op.drop_column('schools', 'academic_year_start')
    
    # Step 4: Rename the temporary column
    op.alter_column('schools', 'academic_year_start_temp', new_column_name='academic_year_start')
    
    # Step 5: Add NOT NULL constraint
    op.alter_column('schools', 'academic_year_start', nullable=False)
    
    # Handle other column changes
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'roles_csv',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'roles_csv',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    
    # FIXED: Handle the downgrade conversion from date back to integer
    # Step 1: Add temporary integer column
    op.add_column('schools', sa.Column('academic_year_start_temp', sa.Integer(), nullable=True))
    
    # Step 2: Extract year from date
    op.execute("""
        UPDATE schools 
        SET academic_year_start_temp = EXTRACT(YEAR FROM academic_year_start)
        WHERE academic_year_start IS NOT NULL
    """)
    
    # Step 3: Drop the date column
    op.drop_column('schools', 'academic_year_start')
    
    # Step 4: Rename the temporary column
    op.alter_column('schools', 'academic_year_start_temp', new_column_name='academic_year_start')
    
    # Step 5: Add NOT NULL constraint
    op.alter_column('schools', 'academic_year_start', nullable=False)
    
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('roles_csv', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###